//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:54:44 PM CEST 
//


package generated_ifcm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}creationDate"/>
 *         &lt;element ref="{}author"/>
 *         &lt;element ref="{}organization"/>
 *         &lt;element ref="{}preprocessor"/>
 *         &lt;element ref="{}originatingSystem"/>
 *         &lt;element ref="{}authorization"/>
 *         &lt;element ref="{}fileSchema"/>
 *         &lt;element ref="{}viewDefinition"/>
 *         &lt;element ref="{}exportOptions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "creationDate",
    "author",
    "organization",
    "preprocessor",
    "originatingSystem",
    "authorization",
    "fileSchema",
    "viewDefinition",
    "exportOptions"
})
@XmlRootElement(name = "header")
public class Header {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected XMLGregorianCalendar creationDate;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected String organization;
    @XmlElement(required = true)
    protected String preprocessor;
    @XmlElement(required = true)
    protected String originatingSystem;
    @XmlElement(required = true)
    protected String authorization;
    @XmlElement(required = true)
    protected String fileSchema;
    @XmlElement(required = true)
    protected String viewDefinition;
    @XmlElement(required = true)
    protected String exportOptions;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganization(String value) {
        this.organization = value;
    }

    /**
     * Gets the value of the preprocessor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreprocessor() {
        return preprocessor;
    }

    /**
     * Sets the value of the preprocessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreprocessor(String value) {
        this.preprocessor = value;
    }

    /**
     * Gets the value of the originatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatingSystem() {
        return originatingSystem;
    }

    /**
     * Sets the value of the originatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatingSystem(String value) {
        this.originatingSystem = value;
    }

    /**
     * Gets the value of the authorization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorization() {
        return authorization;
    }

    /**
     * Sets the value of the authorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorization(String value) {
        this.authorization = value;
    }

    /**
     * Gets the value of the fileSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileSchema() {
        return fileSchema;
    }

    /**
     * Sets the value of the fileSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileSchema(String value) {
        this.fileSchema = value;
    }

    /**
     * Gets the value of the viewDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewDefinition() {
        return viewDefinition;
    }

    /**
     * Sets the value of the viewDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewDefinition(String value) {
        this.viewDefinition = value;
    }

    /**
     * Gets the value of the exportOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportOptions() {
        return exportOptions;
    }

    /**
     * Sets the value of the exportOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportOptions(String value) {
        this.exportOptions = value;
    }

}
