//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:54:44 PM CEST 
//


package generated_ifcm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ifcApplication"/>
 *         &lt;element ref="{}IfcGeometricRepresentationContext"/>
 *         &lt;element ref="{}ifcSiUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ifcApplication",
    "ifcGeometricRepresentationContext",
    "ifcSiUnit"
})
@XmlRootElement(name = "ifcparameters")
public class Ifcparameters {

    @XmlElement(required = true)
    protected String ifcApplication;
    @XmlElement(name = "IfcGeometricRepresentationContext", required = true)
    protected String ifcGeometricRepresentationContext;
    @XmlElement(required = true)
    protected String ifcSiUnit;

    /**
     * Gets the value of the ifcApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfcApplication() {
        return ifcApplication;
    }

    /**
     * Sets the value of the ifcApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfcApplication(String value) {
        this.ifcApplication = value;
    }

    /**
     * Gets the value of the ifcGeometricRepresentationContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfcGeometricRepresentationContext() {
        return ifcGeometricRepresentationContext;
    }

    /**
     * Sets the value of the ifcGeometricRepresentationContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfcGeometricRepresentationContext(String value) {
        this.ifcGeometricRepresentationContext = value;
    }

    /**
     * Gets the value of the ifcSiUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfcSiUnit() {
        return ifcSiUnit;
    }

    /**
     * Sets the value of the ifcSiUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfcSiUnit(String value) {
        this.ifcSiUnit = value;
    }

}
