//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:54:44 PM CEST 
//


package generated_ifcm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}numberOfEntityTypesUsed"/>
 *         &lt;element ref="{}numberOfTotalEntitiesUsed"/>
 *         &lt;element ref="{}optionalAttributes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numberOfEntityTypesUsed",
    "numberOfTotalEntitiesUsed",
    "optionalAttributes"
})
@XmlRootElement(name = "informationMetric")
public class InformationMetric {

    protected short numberOfEntityTypesUsed;
    protected short numberOfTotalEntitiesUsed;
    protected byte optionalAttributes;

    /**
     * Gets the value of the numberOfEntityTypesUsed property.
     * 
     */
    public short getNumberOfEntityTypesUsed() {
        return numberOfEntityTypesUsed;
    }

    /**
     * Sets the value of the numberOfEntityTypesUsed property.
     * 
     */
    public void setNumberOfEntityTypesUsed(short value) {
        this.numberOfEntityTypesUsed = value;
    }

    /**
     * Gets the value of the numberOfTotalEntitiesUsed property.
     * 
     */
    public short getNumberOfTotalEntitiesUsed() {
        return numberOfTotalEntitiesUsed;
    }

    /**
     * Sets the value of the numberOfTotalEntitiesUsed property.
     * 
     */
    public void setNumberOfTotalEntitiesUsed(short value) {
        this.numberOfTotalEntitiesUsed = value;
    }

    /**
     * Gets the value of the optionalAttributes property.
     * 
     */
    public byte getOptionalAttributes() {
        return optionalAttributes;
    }

    /**
     * Sets the value of the optionalAttributes property.
     * 
     */
    public void setOptionalAttributes(byte value) {
        this.optionalAttributes = value;
    }

}
