//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:54:44 PM CEST 
//


package generated_ifcm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated_ifcm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FloorCount_QNAME = new QName("", "floorCount");
    private final static QName _OriginatingSystem_QNAME = new QName("", "originatingSystem");
    private final static QName _ExportOptions_QNAME = new QName("", "exportOptions");
    private final static QName _Authorization_QNAME = new QName("", "authorization");
    private final static QName _Preprocessor_QNAME = new QName("", "preprocessor");
    private final static QName _Author_QNAME = new QName("", "author");
    private final static QName _Organization_QNAME = new QName("", "organization");
    private final static QName _ColumnCount_QNAME = new QName("", "columnCount");
    private final static QName _RoomCount_QNAME = new QName("", "roomCount");
    private final static QName _WebResourceLink_QNAME = new QName("", "webResourceLink");
    private final static QName _NumberOfComponents_QNAME = new QName("", "numberOfComponents");
    private final static QName _IfcSiUnit_QNAME = new QName("", "ifcSiUnit");
    private final static QName _WindowsCount_QNAME = new QName("", "windowsCount");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _NumberOfRelations_QNAME = new QName("", "numberOfRelations");
    private final static QName _FileSchema_QNAME = new QName("", "fileSchema");
    private final static QName _DoorCount_QNAME = new QName("", "doorCount");
    private final static QName _IfcApplication_QNAME = new QName("", "ifcApplication");
    private final static QName _NumberOfActors_QNAME = new QName("", "numberOfActors");
    private final static QName _ViewDefinition_QNAME = new QName("", "viewDefinition");
    private final static QName _PipeCount_QNAME = new QName("", "pipeCount");
    private final static QName _IfcGeometricRepresentationContext_QNAME = new QName("", "IfcGeometricRepresentationContext");
    private final static QName _NumberOfEntityTypesUsed_QNAME = new QName("", "numberOfEntityTypesUsed");
    private final static QName _NumberOfTotalEntitiesUsed_QNAME = new QName("", "numberOfTotalEntitiesUsed");
    private final static QName _OptionalAttributes_QNAME = new QName("", "optionalAttributes");
    private final static QName _CreationDate_QNAME = new QName("", "creationDate");
    private final static QName _WallCount_QNAME = new QName("", "wallCount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated_ifcm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ifcparameters }
     * 
     */
    public Ifcparameters createIfcparameters() {
        return new Ifcparameters();
    }

    /**
     * Create an instance of {@link Quantities }
     * 
     */
    public Quantities createQuantities() {
        return new Quantities();
    }

    /**
     * Create an instance of {@link Ifcm }
     * 
     */
    public Ifcm createIfcm() {
        return new Ifcm();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link InformationMetric }
     * 
     */
    public InformationMetric createInformationMetric() {
        return new InformationMetric();
    }

    /**
     * Create an instance of {@link Dependencies }
     * 
     */
    public Dependencies createDependencies() {
        return new Dependencies();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "floorCount")
    public JAXBElement<Byte> createFloorCount(Byte value) {
        return new JAXBElement<Byte>(_FloorCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "originatingSystem")
    public JAXBElement<String> createOriginatingSystem(String value) {
        return new JAXBElement<String>(_OriginatingSystem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exportOptions")
    public JAXBElement<String> createExportOptions(String value) {
        return new JAXBElement<String>(_ExportOptions_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "authorization")
    public JAXBElement<String> createAuthorization(String value) {
        return new JAXBElement<String>(_Authorization_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "preprocessor")
    public JAXBElement<String> createPreprocessor(String value) {
        return new JAXBElement<String>(_Preprocessor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "organization")
    public JAXBElement<String> createOrganization(String value) {
        return new JAXBElement<String>(_Organization_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "columnCount")
    public JAXBElement<Byte> createColumnCount(Byte value) {
        return new JAXBElement<Byte>(_ColumnCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "roomCount")
    public JAXBElement<Byte> createRoomCount(Byte value) {
        return new JAXBElement<Byte>(_RoomCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "webResourceLink")
    public JAXBElement<String> createWebResourceLink(String value) {
        return new JAXBElement<String>(_WebResourceLink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfComponents")
    public JAXBElement<Short> createNumberOfComponents(Short value) {
        return new JAXBElement<Short>(_NumberOfComponents_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ifcSiUnit")
    public JAXBElement<String> createIfcSiUnit(String value) {
        return new JAXBElement<String>(_IfcSiUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "windowsCount")
    public JAXBElement<Byte> createWindowsCount(Byte value) {
        return new JAXBElement<Byte>(_WindowsCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfRelations")
    public JAXBElement<Short> createNumberOfRelations(Short value) {
        return new JAXBElement<Short>(_NumberOfRelations_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fileSchema")
    public JAXBElement<String> createFileSchema(String value) {
        return new JAXBElement<String>(_FileSchema_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "doorCount")
    public JAXBElement<Byte> createDoorCount(Byte value) {
        return new JAXBElement<Byte>(_DoorCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ifcApplication")
    public JAXBElement<String> createIfcApplication(String value) {
        return new JAXBElement<String>(_IfcApplication_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfActors")
    public JAXBElement<Byte> createNumberOfActors(Byte value) {
        return new JAXBElement<Byte>(_NumberOfActors_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "viewDefinition")
    public JAXBElement<String> createViewDefinition(String value) {
        return new JAXBElement<String>(_ViewDefinition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pipeCount")
    public JAXBElement<Byte> createPipeCount(Byte value) {
        return new JAXBElement<Byte>(_PipeCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IfcGeometricRepresentationContext")
    public JAXBElement<String> createIfcGeometricRepresentationContext(String value) {
        return new JAXBElement<String>(_IfcGeometricRepresentationContext_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfEntityTypesUsed")
    public JAXBElement<Short> createNumberOfEntityTypesUsed(Short value) {
        return new JAXBElement<Short>(_NumberOfEntityTypesUsed_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfTotalEntitiesUsed")
    public JAXBElement<Short> createNumberOfTotalEntitiesUsed(Short value) {
        return new JAXBElement<Short>(_NumberOfTotalEntitiesUsed_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optionalAttributes")
    public JAXBElement<Byte> createOptionalAttributes(Byte value) {
        return new JAXBElement<Byte>(_OptionalAttributes_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creationDate")
    public JAXBElement<XMLGregorianCalendar> createCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wallCount")
    public JAXBElement<Short> createWallCount(Short value) {
        return new JAXBElement<Short>(_WallCount_QNAME, Short.class, null, value);
    }

}
