//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:54:44 PM CEST 
//


package generated_ifcm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}floorCount"/>
 *         &lt;element ref="{}roomCount"/>
 *         &lt;element ref="{}wallCount"/>
 *         &lt;element ref="{}windowsCount"/>
 *         &lt;element ref="{}doorCount"/>
 *         &lt;element ref="{}pipeCount"/>
 *         &lt;element ref="{}columnCount"/>
 *         &lt;element ref="{}numberOfComponents"/>
 *         &lt;element ref="{}numberOfRelations"/>
 *         &lt;element ref="{}numberOfActors"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "floorCount",
    "roomCount",
    "wallCount",
    "windowsCount",
    "doorCount",
    "pipeCount",
    "columnCount",
    "numberOfComponents",
    "numberOfRelations",
    "numberOfActors"
})
@XmlRootElement(name = "quantities")
public class Quantities {

    protected byte floorCount;
    protected byte roomCount;
    protected short wallCount;
    protected byte windowsCount;
    protected byte doorCount;
    protected byte pipeCount;
    protected byte columnCount;
    protected short numberOfComponents;
    protected short numberOfRelations;
    protected byte numberOfActors;

    /**
     * Gets the value of the floorCount property.
     * 
     */
    public byte getFloorCount() {
        return floorCount;
    }

    /**
     * Sets the value of the floorCount property.
     * 
     */
    public void setFloorCount(byte value) {
        this.floorCount = value;
    }

    /**
     * Gets the value of the roomCount property.
     * 
     */
    public byte getRoomCount() {
        return roomCount;
    }

    /**
     * Sets the value of the roomCount property.
     * 
     */
    public void setRoomCount(byte value) {
        this.roomCount = value;
    }

    /**
     * Gets the value of the wallCount property.
     * 
     */
    public short getWallCount() {
        return wallCount;
    }

    /**
     * Sets the value of the wallCount property.
     * 
     */
    public void setWallCount(short value) {
        this.wallCount = value;
    }

    /**
     * Gets the value of the windowsCount property.
     * 
     */
    public byte getWindowsCount() {
        return windowsCount;
    }

    /**
     * Sets the value of the windowsCount property.
     * 
     */
    public void setWindowsCount(byte value) {
        this.windowsCount = value;
    }

    /**
     * Gets the value of the doorCount property.
     * 
     */
    public byte getDoorCount() {
        return doorCount;
    }

    /**
     * Sets the value of the doorCount property.
     * 
     */
    public void setDoorCount(byte value) {
        this.doorCount = value;
    }

    /**
     * Gets the value of the pipeCount property.
     * 
     */
    public byte getPipeCount() {
        return pipeCount;
    }

    /**
     * Sets the value of the pipeCount property.
     * 
     */
    public void setPipeCount(byte value) {
        this.pipeCount = value;
    }

    /**
     * Gets the value of the columnCount property.
     * 
     */
    public byte getColumnCount() {
        return columnCount;
    }

    /**
     * Sets the value of the columnCount property.
     * 
     */
    public void setColumnCount(byte value) {
        this.columnCount = value;
    }

    /**
     * Gets the value of the numberOfComponents property.
     * 
     */
    public short getNumberOfComponents() {
        return numberOfComponents;
    }

    /**
     * Sets the value of the numberOfComponents property.
     * 
     */
    public void setNumberOfComponents(short value) {
        this.numberOfComponents = value;
    }

    /**
     * Gets the value of the numberOfRelations property.
     * 
     */
    public short getNumberOfRelations() {
        return numberOfRelations;
    }

    /**
     * Sets the value of the numberOfRelations property.
     * 
     */
    public void setNumberOfRelations(short value) {
        this.numberOfRelations = value;
    }

    /**
     * Gets the value of the numberOfActors property.
     * 
     */
    public byte getNumberOfActors() {
        return numberOfActors;
    }

    /**
     * Sets the value of the numberOfActors property.
     * 
     */
    public void setNumberOfActors(byte value) {
        this.numberOfActors = value;
    }

}
