//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}angle_minimum"/>
 *         &lt;element ref="{}angle_maximum"/>
 *         &lt;element ref="{}angle_scaled_integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "angleMinimum",
    "angleMaximum",
    "angleScaledInteger"
})
@XmlRootElement(name = "angles")
public class Angles {

    @XmlElement(name = "angle_minimum")
    protected byte angleMinimum;
    @XmlElement(name = "angle_maximum")
    protected byte angleMaximum;
    @XmlElement(name = "angle_scaled_integer")
    protected byte angleScaledInteger;

    /**
     * Gets the value of the angleMinimum property.
     * 
     */
    public byte getAngleMinimum() {
        return angleMinimum;
    }

    /**
     * Sets the value of the angleMinimum property.
     * 
     */
    public void setAngleMinimum(byte value) {
        this.angleMinimum = value;
    }

    /**
     * Gets the value of the angleMaximum property.
     * 
     */
    public byte getAngleMaximum() {
        return angleMaximum;
    }

    /**
     * Sets the value of the angleMaximum property.
     * 
     */
    public void setAngleMaximum(byte value) {
        this.angleMaximum = value;
    }

    /**
     * Gets the value of the angleScaledInteger property.
     * 
     */
    public byte getAngleScaledInteger() {
        return angleScaledInteger;
    }

    /**
     * Sets the value of the angleScaledInteger property.
     * 
     */
    public void setAngleScaledInteger(byte value) {
        this.angleScaledInteger = value;
    }

}
