//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}cartesian_x_field"/>
 *         &lt;element ref="{}cartesian_y_field"/>
 *         &lt;element ref="{}cartesian_z_field"/>
 *         &lt;element ref="{}cartesian_invalid_state_field"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cartesianXField",
    "cartesianYField",
    "cartesianZField",
    "cartesianInvalidStateField"
})
@XmlRootElement(name = "cartesian_fields")
public class CartesianFields {

    @XmlElement(name = "cartesian_x_field")
    protected boolean cartesianXField;
    @XmlElement(name = "cartesian_y_field")
    protected boolean cartesianYField;
    @XmlElement(name = "cartesian_z_field")
    protected boolean cartesianZField;
    @XmlElement(name = "cartesian_invalid_state_field")
    protected boolean cartesianInvalidStateField;

    /**
     * Gets the value of the cartesianXField property.
     * 
     */
    public boolean isCartesianXField() {
        return cartesianXField;
    }

    /**
     * Sets the value of the cartesianXField property.
     * 
     */
    public void setCartesianXField(boolean value) {
        this.cartesianXField = value;
    }

    /**
     * Gets the value of the cartesianYField property.
     * 
     */
    public boolean isCartesianYField() {
        return cartesianYField;
    }

    /**
     * Sets the value of the cartesianYField property.
     * 
     */
    public void setCartesianYField(boolean value) {
        this.cartesianYField = value;
    }

    /**
     * Gets the value of the cartesianZField property.
     * 
     */
    public boolean isCartesianZField() {
        return cartesianZField;
    }

    /**
     * Sets the value of the cartesianZField property.
     * 
     */
    public void setCartesianZField(boolean value) {
        this.cartesianZField = value;
    }

    /**
     * Gets the value of the cartesianInvalidStateField property.
     * 
     */
    public boolean isCartesianInvalidStateField() {
        return cartesianInvalidStateField;
    }

    /**
     * Sets the value of the cartesianInvalidStateField property.
     * 
     */
    public void setCartesianInvalidStateField(boolean value) {
        this.cartesianInvalidStateField = value;
    }

}
