//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}guid"/>
 *         &lt;element ref="{}representation"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}acquisition_datetime"/>
 *         &lt;element ref="{}associated_data3D_guid"/>
 *         &lt;element ref="{}sensor_vendor"/>
 *         &lt;element ref="{}sensor_model"/>
 *         &lt;element ref="{}sensor_serial_number"/>
 *         &lt;element ref="{}pose"/>
 *         &lt;element ref="{}visual_ref_representation"/>
 *         &lt;element ref="{}spherical_representation"/>
 *         &lt;element ref="{}pinhole_representation"/>
 *         &lt;element ref="{}cylindrical_representation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "guid",
    "representation",
    "description",
    "acquisitionDatetime",
    "associatedData3DGuid",
    "sensorVendor",
    "sensorModel",
    "sensorSerialNumber",
    "pose",
    "visualRefRepresentation",
    "sphericalRepresentation",
    "pinholeRepresentation",
    "cylindricalRepresentation"
})
@XmlRootElement(name = "e57image")
public class E57Image {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected String representation;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "acquisition_datetime", required = true)
    protected XMLGregorianCalendar acquisitionDatetime;
    @XmlElement(name = "associated_data3D_guid", required = true)
    protected String associatedData3DGuid;
    @XmlElement(name = "sensor_vendor", required = true)
    protected String sensorVendor;
    @XmlElement(name = "sensor_model", required = true)
    protected String sensorModel;
    @XmlElement(name = "sensor_serial_number", required = true)
    protected String sensorSerialNumber;
    @XmlElement(required = true)
    protected Pose pose;
    @XmlElement(name = "visual_ref_representation", required = true)
    protected VisualRefRepresentation visualRefRepresentation;
    @XmlElement(name = "spherical_representation", required = true)
    protected SphericalRepresentation sphericalRepresentation;
    @XmlElement(name = "pinhole_representation", required = true)
    protected PinholeRepresentation pinholeRepresentation;
    @XmlElement(name = "cylindrical_representation", required = true)
    protected CylindricalRepresentation cylindricalRepresentation;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the representation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentation() {
        return representation;
    }

    /**
     * Sets the value of the representation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentation(String value) {
        this.representation = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the acquisitionDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcquisitionDatetime() {
        return acquisitionDatetime;
    }

    /**
     * Sets the value of the acquisitionDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcquisitionDatetime(XMLGregorianCalendar value) {
        this.acquisitionDatetime = value;
    }

    /**
     * Gets the value of the associatedData3DGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedData3DGuid() {
        return associatedData3DGuid;
    }

    /**
     * Sets the value of the associatedData3DGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedData3DGuid(String value) {
        this.associatedData3DGuid = value;
    }

    /**
     * Gets the value of the sensorVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorVendor() {
        return sensorVendor;
    }

    /**
     * Sets the value of the sensorVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorVendor(String value) {
        this.sensorVendor = value;
    }

    /**
     * Gets the value of the sensorModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorModel() {
        return sensorModel;
    }

    /**
     * Sets the value of the sensorModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorModel(String value) {
        this.sensorModel = value;
    }

    /**
     * Gets the value of the sensorSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorSerialNumber() {
        return sensorSerialNumber;
    }

    /**
     * Sets the value of the sensorSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorSerialNumber(String value) {
        this.sensorSerialNumber = value;
    }

    /**
     * Gets the value of the pose property.
     * 
     * @return
     *     possible object is
     *     {@link Pose }
     *     
     */
    public Pose getPose() {
        return pose;
    }

    /**
     * Sets the value of the pose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pose }
     *     
     */
    public void setPose(Pose value) {
        this.pose = value;
    }

    /**
     * Gets the value of the visualRefRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link VisualRefRepresentation }
     *     
     */
    public VisualRefRepresentation getVisualRefRepresentation() {
        return visualRefRepresentation;
    }

    /**
     * Sets the value of the visualRefRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisualRefRepresentation }
     *     
     */
    public void setVisualRefRepresentation(VisualRefRepresentation value) {
        this.visualRefRepresentation = value;
    }

    /**
     * Gets the value of the sphericalRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link SphericalRepresentation }
     *     
     */
    public SphericalRepresentation getSphericalRepresentation() {
        return sphericalRepresentation;
    }

    /**
     * Sets the value of the sphericalRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SphericalRepresentation }
     *     
     */
    public void setSphericalRepresentation(SphericalRepresentation value) {
        this.sphericalRepresentation = value;
    }

    /**
     * Gets the value of the pinholeRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link PinholeRepresentation }
     *     
     */
    public PinholeRepresentation getPinholeRepresentation() {
        return pinholeRepresentation;
    }

    /**
     * Sets the value of the pinholeRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PinholeRepresentation }
     *     
     */
    public void setPinholeRepresentation(PinholeRepresentation value) {
        this.pinholeRepresentation = value;
    }

    /**
     * Gets the value of the cylindricalRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link CylindricalRepresentation }
     *     
     */
    public CylindricalRepresentation getCylindricalRepresentation() {
        return cylindricalRepresentation;
    }

    /**
     * Sets the value of the cylindricalRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CylindricalRepresentation }
     *     
     */
    public void setCylindricalRepresentation(CylindricalRepresentation value) {
        this.cylindricalRepresentation = value;
    }

}
