//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}E57root"/>
 *         &lt;element ref="{}e57scan"/>
 *         &lt;element ref="{}e57image"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "e57Root",
    "e57Scan",
    "e57Image"
})
@XmlRootElement(name = "e57m")
public class E57M {

    @XmlElement(name = "E57root", required = true)
    protected E57Root e57Root;
    @XmlElement(name = "e57scan", required = true)
    protected E57Scan e57Scan;
    @XmlElement(name = "e57image", required = true)
    protected E57Image e57Image;

    /**
     * Gets the value of the e57Root property.
     * 
     * @return
     *     possible object is
     *     {@link E57Root }
     *     
     */
    public E57Root getE57Root() {
        return e57Root;
    }

    /**
     * Sets the value of the e57Root property.
     * 
     * @param value
     *     allowed object is
     *     {@link E57Root }
     *     
     */
    public void setE57Root(E57Root value) {
        this.e57Root = value;
    }

    /**
     * Gets the value of the e57Scan property.
     * 
     * @return
     *     possible object is
     *     {@link E57Scan }
     *     
     */
    public E57Scan getE57Scan() {
        return e57Scan;
    }

    /**
     * Sets the value of the e57Scan property.
     * 
     * @param value
     *     allowed object is
     *     {@link E57Scan }
     *     
     */
    public void setE57Scan(E57Scan value) {
        this.e57Scan = value;
    }

    /**
     * Gets the value of the e57Image property.
     * 
     * @return
     *     possible object is
     *     {@link E57Image }
     *     
     */
    public E57Image getE57Image() {
        return e57Image;
    }

    /**
     * Sets the value of the e57Image property.
     * 
     * @param value
     *     allowed object is
     *     {@link E57Image }
     *     
     */
    public void setE57Image(E57Image value) {
        this.e57Image = value;
    }

}
