//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}guid"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}original_guids"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}sensor_vendor"/>
 *         &lt;element ref="{}sensor_model"/>
 *         &lt;element ref="{}sensor_serial_number"/>
 *         &lt;element ref="{}sensor_hardware_version"/>
 *         &lt;element ref="{}sensor_software_version"/>
 *         &lt;element ref="{}sensor_firmware_version"/>
 *         &lt;element ref="{}temperature"/>
 *         &lt;element ref="{}relative_humidity"/>
 *         &lt;element ref="{}atmospheric_pressure"/>
 *         &lt;element ref="{}acquisition_start"/>
 *         &lt;element ref="{}acquisition_end"/>
 *         &lt;element ref="{}pose"/>
 *         &lt;element ref="{}index_bounds"/>
 *         &lt;element ref="{}cartesian_bounds"/>
 *         &lt;element ref="{}sphericalbounds"/>
 *         &lt;element ref="{}intensity_limits"/>
 *         &lt;element ref="{}color_limits"/>
 *         &lt;element ref="{}pointSize"/>
 *         &lt;element ref="{}point_fields"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guid",
    "name",
    "originalGuids",
    "description",
    "sensorVendor",
    "sensorModel",
    "sensorSerialNumber",
    "sensorHardwareVersion",
    "sensorSoftwareVersion",
    "sensorFirmwareVersion",
    "temperature",
    "relativeHumidity",
    "atmosphericPressure",
    "acquisitionStart",
    "acquisitionEnd",
    "pose",
    "indexBounds",
    "cartesianBounds",
    "sphericalbounds",
    "intensityLimits",
    "colorLimits",
    "pointSize",
    "pointFields"
})
@XmlRootElement(name = "e57scan")
public class E57Scan {

    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "original_guids", required = true)
    protected String originalGuids;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "sensor_vendor", required = true)
    protected String sensorVendor;
    @XmlElement(name = "sensor_model", required = true)
    protected String sensorModel;
    @XmlElement(name = "sensor_serial_number", required = true)
    protected String sensorSerialNumber;
    @XmlElement(name = "sensor_hardware_version", required = true)
    protected String sensorHardwareVersion;
    @XmlElement(name = "sensor_software_version", required = true)
    protected String sensorSoftwareVersion;
    @XmlElement(name = "sensor_firmware_version", required = true)
    protected String sensorFirmwareVersion;
    @XmlElement(required = true)
    protected BigDecimal temperature;
    @XmlElement(name = "relative_humidity")
    protected byte relativeHumidity;
    @XmlElement(name = "atmospheric_pressure")
    protected int atmosphericPressure;
    @XmlElement(name = "acquisition_start", required = true)
    protected XMLGregorianCalendar acquisitionStart;
    @XmlElement(name = "acquisition_end", required = true)
    protected XMLGregorianCalendar acquisitionEnd;
    @XmlElement(required = true)
    protected Pose pose;
    @XmlElement(name = "index_bounds", required = true)
    protected IndexBounds indexBounds;
    @XmlElement(name = "cartesian_bounds", required = true)
    protected CartesianBounds cartesianBounds;
    @XmlElement(required = true)
    protected Sphericalbounds sphericalbounds;
    @XmlElement(name = "intensity_limits", required = true)
    protected IntensityLimits intensityLimits;
    @XmlElement(name = "color_limits", required = true)
    protected ColorLimits colorLimits;
    protected int pointSize;
    @XmlElement(name = "point_fields", required = true)
    protected PointFields pointFields;

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the originalGuids property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalGuids() {
        return originalGuids;
    }

    /**
     * Sets the value of the originalGuids property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalGuids(String value) {
        this.originalGuids = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the sensorVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorVendor() {
        return sensorVendor;
    }

    /**
     * Sets the value of the sensorVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorVendor(String value) {
        this.sensorVendor = value;
    }

    /**
     * Gets the value of the sensorModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorModel() {
        return sensorModel;
    }

    /**
     * Sets the value of the sensorModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorModel(String value) {
        this.sensorModel = value;
    }

    /**
     * Gets the value of the sensorSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorSerialNumber() {
        return sensorSerialNumber;
    }

    /**
     * Sets the value of the sensorSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorSerialNumber(String value) {
        this.sensorSerialNumber = value;
    }

    /**
     * Gets the value of the sensorHardwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorHardwareVersion() {
        return sensorHardwareVersion;
    }

    /**
     * Sets the value of the sensorHardwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorHardwareVersion(String value) {
        this.sensorHardwareVersion = value;
    }

    /**
     * Gets the value of the sensorSoftwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorSoftwareVersion() {
        return sensorSoftwareVersion;
    }

    /**
     * Sets the value of the sensorSoftwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorSoftwareVersion(String value) {
        this.sensorSoftwareVersion = value;
    }

    /**
     * Gets the value of the sensorFirmwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorFirmwareVersion() {
        return sensorFirmwareVersion;
    }

    /**
     * Sets the value of the sensorFirmwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorFirmwareVersion(String value) {
        this.sensorFirmwareVersion = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperature(BigDecimal value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the relativeHumidity property.
     * 
     */
    public byte getRelativeHumidity() {
        return relativeHumidity;
    }

    /**
     * Sets the value of the relativeHumidity property.
     * 
     */
    public void setRelativeHumidity(byte value) {
        this.relativeHumidity = value;
    }

    /**
     * Gets the value of the atmosphericPressure property.
     * 
     */
    public int getAtmosphericPressure() {
        return atmosphericPressure;
    }

    /**
     * Sets the value of the atmosphericPressure property.
     * 
     */
    public void setAtmosphericPressure(int value) {
        this.atmosphericPressure = value;
    }

    /**
     * Gets the value of the acquisitionStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcquisitionStart() {
        return acquisitionStart;
    }

    /**
     * Sets the value of the acquisitionStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcquisitionStart(XMLGregorianCalendar value) {
        this.acquisitionStart = value;
    }

    /**
     * Gets the value of the acquisitionEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcquisitionEnd() {
        return acquisitionEnd;
    }

    /**
     * Sets the value of the acquisitionEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcquisitionEnd(XMLGregorianCalendar value) {
        this.acquisitionEnd = value;
    }

    /**
     * Gets the value of the pose property.
     * 
     * @return
     *     possible object is
     *     {@link Pose }
     *     
     */
    public Pose getPose() {
        return pose;
    }

    /**
     * Sets the value of the pose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pose }
     *     
     */
    public void setPose(Pose value) {
        this.pose = value;
    }

    /**
     * Gets the value of the indexBounds property.
     * 
     * @return
     *     possible object is
     *     {@link IndexBounds }
     *     
     */
    public IndexBounds getIndexBounds() {
        return indexBounds;
    }

    /**
     * Sets the value of the indexBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexBounds }
     *     
     */
    public void setIndexBounds(IndexBounds value) {
        this.indexBounds = value;
    }

    /**
     * Gets the value of the cartesianBounds property.
     * 
     * @return
     *     possible object is
     *     {@link CartesianBounds }
     *     
     */
    public CartesianBounds getCartesianBounds() {
        return cartesianBounds;
    }

    /**
     * Sets the value of the cartesianBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CartesianBounds }
     *     
     */
    public void setCartesianBounds(CartesianBounds value) {
        this.cartesianBounds = value;
    }

    /**
     * Gets the value of the sphericalbounds property.
     * 
     * @return
     *     possible object is
     *     {@link Sphericalbounds }
     *     
     */
    public Sphericalbounds getSphericalbounds() {
        return sphericalbounds;
    }

    /**
     * Sets the value of the sphericalbounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sphericalbounds }
     *     
     */
    public void setSphericalbounds(Sphericalbounds value) {
        this.sphericalbounds = value;
    }

    /**
     * Gets the value of the intensityLimits property.
     * 
     * @return
     *     possible object is
     *     {@link IntensityLimits }
     *     
     */
    public IntensityLimits getIntensityLimits() {
        return intensityLimits;
    }

    /**
     * Sets the value of the intensityLimits property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntensityLimits }
     *     
     */
    public void setIntensityLimits(IntensityLimits value) {
        this.intensityLimits = value;
    }

    /**
     * Gets the value of the colorLimits property.
     * 
     * @return
     *     possible object is
     *     {@link ColorLimits }
     *     
     */
    public ColorLimits getColorLimits() {
        return colorLimits;
    }

    /**
     * Sets the value of the colorLimits property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorLimits }
     *     
     */
    public void setColorLimits(ColorLimits value) {
        this.colorLimits = value;
    }

    /**
     * Gets the value of the pointSize property.
     * 
     */
    public int getPointSize() {
        return pointSize;
    }

    /**
     * Sets the value of the pointSize property.
     * 
     */
    public void setPointSize(int value) {
        this.pointSize = value;
    }

    /**
     * Gets the value of the pointFields property.
     * 
     * @return
     *     possible object is
     *     {@link PointFields }
     *     
     */
    public PointFields getPointFields() {
        return pointFields;
    }

    /**
     * Sets the value of the pointFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointFields }
     *     
     */
    public void setPointFields(PointFields value) {
        this.pointFields = value;
    }

}
