//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}row_index_field"/>
 *         &lt;element ref="{}row_index_maximum"/>
 *         &lt;element ref="{}column_index_field"/>
 *         &lt;element ref="{}column_index_maximum"/>
 *         &lt;element ref="{}return_index_field"/>
 *         &lt;element ref="{}return_count_field"/>
 *         &lt;element ref="{}return_maximum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rowIndexField",
    "rowIndexMaximum",
    "columnIndexField",
    "columnIndexMaximum",
    "returnIndexField",
    "returnCountField",
    "returnMaximum"
})
@XmlRootElement(name = "index_fields")
public class IndexFields {

    @XmlElement(name = "row_index_field")
    protected boolean rowIndexField;
    @XmlElement(name = "row_index_maximum")
    protected long rowIndexMaximum;
    @XmlElement(name = "column_index_field")
    protected boolean columnIndexField;
    @XmlElement(name = "column_index_maximum")
    protected long columnIndexMaximum;
    @XmlElement(name = "return_index_field")
    protected boolean returnIndexField;
    @XmlElement(name = "return_count_field")
    protected boolean returnCountField;
    @XmlElement(name = "return_maximum")
    protected byte returnMaximum;

    /**
     * Gets the value of the rowIndexField property.
     * 
     */
    public boolean isRowIndexField() {
        return rowIndexField;
    }

    /**
     * Sets the value of the rowIndexField property.
     * 
     */
    public void setRowIndexField(boolean value) {
        this.rowIndexField = value;
    }

    /**
     * Gets the value of the rowIndexMaximum property.
     * 
     */
    public long getRowIndexMaximum() {
        return rowIndexMaximum;
    }

    /**
     * Sets the value of the rowIndexMaximum property.
     * 
     */
    public void setRowIndexMaximum(long value) {
        this.rowIndexMaximum = value;
    }

    /**
     * Gets the value of the columnIndexField property.
     * 
     */
    public boolean isColumnIndexField() {
        return columnIndexField;
    }

    /**
     * Sets the value of the columnIndexField property.
     * 
     */
    public void setColumnIndexField(boolean value) {
        this.columnIndexField = value;
    }

    /**
     * Gets the value of the columnIndexMaximum property.
     * 
     */
    public long getColumnIndexMaximum() {
        return columnIndexMaximum;
    }

    /**
     * Sets the value of the columnIndexMaximum property.
     * 
     */
    public void setColumnIndexMaximum(long value) {
        this.columnIndexMaximum = value;
    }

    /**
     * Gets the value of the returnIndexField property.
     * 
     */
    public boolean isReturnIndexField() {
        return returnIndexField;
    }

    /**
     * Sets the value of the returnIndexField property.
     * 
     */
    public void setReturnIndexField(boolean value) {
        this.returnIndexField = value;
    }

    /**
     * Gets the value of the returnCountField property.
     * 
     */
    public boolean isReturnCountField() {
        return returnCountField;
    }

    /**
     * Sets the value of the returnCountField property.
     * 
     */
    public void setReturnCountField(boolean value) {
        this.returnCountField = value;
    }

    /**
     * Gets the value of the returnMaximum property.
     * 
     */
    public byte getReturnMaximum() {
        return returnMaximum;
    }

    /**
     * Sets the value of the returnMaximum property.
     * 
     */
    public void setReturnMaximum(byte value) {
        this.returnMaximum = value;
    }

}
