//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}intensity_minimum"/>
 *         &lt;element ref="{}intensity_maximum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "intensityMinimum",
    "intensityMaximum"
})
@XmlRootElement(name = "intensity_limits")
public class IntensityLimits {

    @XmlElement(name = "intensity_minimum")
    protected byte intensityMinimum;
    @XmlElement(name = "intensity_maximum")
    protected byte intensityMaximum;

    /**
     * Gets the value of the intensityMinimum property.
     * 
     */
    public byte getIntensityMinimum() {
        return intensityMinimum;
    }

    /**
     * Sets the value of the intensityMinimum property.
     * 
     */
    public void setIntensityMinimum(byte value) {
        this.intensityMinimum = value;
    }

    /**
     * Gets the value of the intensityMaximum property.
     * 
     */
    public byte getIntensityMaximum() {
        return intensityMaximum;
    }

    /**
     * Sets the value of the intensityMaximum property.
     * 
     */
    public void setIntensityMaximum(byte value) {
        this.intensityMaximum = value;
    }

}
