//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FocalLength_QNAME = new QName("", "focal_length");
    private final static QName _CartesianInvalidStateField_QNAME = new QName("", "cartesian_invalid_state_field");
    private final static QName _CartesianYField_QNAME = new QName("", "cartesian_y_field");
    private final static QName _PointSize_QNAME = new QName("", "pointSize");
    private final static QName _Temperature_QNAME = new QName("", "temperature");
    private final static QName _RangeMaximum_QNAME = new QName("", "range_maximum");
    private final static QName _ImageSize_QNAME = new QName("", "image_size");
    private final static QName _IsColorInvalidField_QNAME = new QName("", "is_color_invalid_field");
    private final static QName _IntensityField_QNAME = new QName("", "intensity_field");
    private final static QName _SensorHardwareVersion_QNAME = new QName("", "sensor_hardware_version");
    private final static QName _CartesianXField_QNAME = new QName("", "cartesian_x_field");
    private final static QName _ScanSize_QNAME = new QName("", "scan_size");
    private final static QName _RelativeHumidity_QNAME = new QName("", "relative_humidity");
    private final static QName _AzimuthMinimum_QNAME = new QName("", "azimuth_minimum");
    private final static QName _SphericalElevationField_QNAME = new QName("", "spherical_elevation_field");
    private final static QName _PrincipalPointY_QNAME = new QName("", "principal_point_y");
    private final static QName _PrincipalPointX_QNAME = new QName("", "principal_point_x");
    private final static QName _AngleScaledInteger_QNAME = new QName("", "angle_scaled_integer");
    private final static QName _ScanCount_QNAME = new QName("", "scan_count");
    private final static QName _ColorRedMinimum_QNAME = new QName("", "color_red_minimum");
    private final static QName _Radius_QNAME = new QName("", "radius");
    private final static QName _ColorBlueMaximum_QNAME = new QName("", "color_blue_maximum");
    private final static QName _PointRangeScaledInteger_QNAME = new QName("", "point_range_scaled_integer");
    private final static QName _ColorRedField_QNAME = new QName("", "color_red_field");
    private final static QName _ImageHeight_QNAME = new QName("", "image_height");
    private final static QName _RowMinimum_QNAME = new QName("", "row_minimum");
    private final static QName _Version_QNAME = new QName("", "version");
    private final static QName _AzimuthMaximum_QNAME = new QName("", "azimuth_maximum");
    private final static QName _IntensityScaledInteger_QNAME = new QName("", "intensity_scaled_integer");
    private final static QName _ReturnIndexField_QNAME = new QName("", "return_index_field");
    private final static QName _ColMinimum_QNAME = new QName("", "col_minimum");
    private final static QName _ImageMaskSize_QNAME = new QName("", "image_mask_size");
    private final static QName _IntensityMinimum_QNAME = new QName("", "intensity_minimum");
    private final static QName _ReturnMaximum_QNAME = new QName("", "return_maximum");
    private final static QName _AngleMaximum_QNAME = new QName("", "angle_maximum");
    private final static QName _OriginalGuids_QNAME = new QName("", "original_guids");
    private final static QName _AcquisitionStart_QNAME = new QName("", "acquisition_start");
    private final static QName _ColumnIndexField_QNAME = new QName("", "column_index_field");
    private final static QName _AcquisitionDatetime_QNAME = new QName("", "acquisition_datetime");
    private final static QName _W_QNAME = new QName("", "w");
    private final static QName _ElevationMaximum_QNAME = new QName("", "elevation_maximum");
    private final static QName _ColumnIndexMaximum_QNAME = new QName("", "column_index_maximum");
    private final static QName _SensorSoftwareVersion_QNAME = new QName("", "sensor_software_version");
    private final static QName _Z_QNAME = new QName("", "z");
    private final static QName _Y_QNAME = new QName("", "y");
    private final static QName _YMaximum_QNAME = new QName("", "y_maximum");
    private final static QName _X_QNAME = new QName("", "x");
    private final static QName _SphericalAzimuthField_QNAME = new QName("", "spherical_azimuth_field");
    private final static QName _PointRangeMinimum_QNAME = new QName("", "point_range_minimum");
    private final static QName _ColorGreenMaximum_QNAME = new QName("", "color_green_maximum");
    private final static QName _ColorGreenMinimum_QNAME = new QName("", "color_green_minimum");
    private final static QName _ReturnCountField_QNAME = new QName("", "return_count_field");
    private final static QName _IsIntensityInvalidField_QNAME = new QName("", "is_intensity_invalid_field");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _ImageWidth_QNAME = new QName("", "image_width");
    private final static QName _SensorSerialNumber_QNAME = new QName("", "sensor_serial_number");
    private final static QName _AcquisitionEnd_QNAME = new QName("", "acquisition_end");
    private final static QName _RowMaximum_QNAME = new QName("", "row_maximum");
    private final static QName _ColorBlueField_QNAME = new QName("", "color_blue_field");
    private final static QName _RowIndexMaximum_QNAME = new QName("", "row_index_maximum");
    private final static QName _CoordinateMetadata_QNAME = new QName("", "coordinate_metadata");
    private final static QName _ZMinimum_QNAME = new QName("", "z_minimum");
    private final static QName _AtmosphericPressure_QNAME = new QName("", "atmospheric_pressure");
    private final static QName _CreationDatetime_QNAME = new QName("", "creation_datetime");
    private final static QName _SphericalInvalidStateField_QNAME = new QName("", "spherical_invalid_state_field");
    private final static QName _ColMaximum_QNAME = new QName("", "col_maximum");
    private final static QName _XMinimum_QNAME = new QName("", "x_minimum");
    private final static QName _SensorFirmwareVersion_QNAME = new QName("", "sensor_firmware_version");
    private final static QName _PixelHeight_QNAME = new QName("", "pixel_height");
    private final static QName _CartesianZField_QNAME = new QName("", "cartesian_z_field");
    private final static QName _Representation_QNAME = new QName("", "representation");
    private final static QName _ColorRedMaximum_QNAME = new QName("", "color_red_maximum");
    private final static QName _TimeMaximum_QNAME = new QName("", "time_Maximum");
    private final static QName _SphericalRangeField_QNAME = new QName("", "spherical_range_field");
    private final static QName _JpegImageSize_QNAME = new QName("", "jpeg_image_size");
    private final static QName _ImageCount_QNAME = new QName("", "image_count");
    private final static QName _ElevationMinimum_QNAME = new QName("", "elevation_minimum");
    private final static QName _TimeStampField_QNAME = new QName("", "time_stamp_field");
    private final static QName _IsTimeStampInvalid_QNAME = new QName("", "is_Time_Stamp_invalid");
    private final static QName _RowIndexField_QNAME = new QName("", "row_index_field");
    private final static QName _SensorVendor_QNAME = new QName("", "sensor_vendor");
    private final static QName _SensorModel_QNAME = new QName("", "sensor_model");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _PixelWidth_QNAME = new QName("", "pixel_width");
    private final static QName _ColorGreenField_QNAME = new QName("", "color_green_field");
    private final static QName _AssociatedData3DGuid_QNAME = new QName("", "associated_data3D_guid");
    private final static QName _PointRangeMaximum_QNAME = new QName("", "point_range_maximum");
    private final static QName _YMinimum_QNAME = new QName("", "y_minimum");
    private final static QName _XMaximum_QNAME = new QName("", "x_maximum");
    private final static QName _PngImageSize_QNAME = new QName("", "png_image_size");
    private final static QName _ZMaximum_QNAME = new QName("", "z_maximum");
    private final static QName _RangeMinimum_QNAME = new QName("", "range_minimum");
    private final static QName _AngleMinimum_QNAME = new QName("", "angle_minimum");
    private final static QName _ColorBlueMinimum_QNAME = new QName("", "color_blue_minimum");
    private final static QName _Guid_QNAME = new QName("", "guid");
    private final static QName _ReturnMinimum_QNAME = new QName("", "return_minimum");
    private final static QName _IntensityMaximum_QNAME = new QName("", "intensity_maximum");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IntensityColorFields }
     * 
     */
    public IntensityColorFields createIntensityColorFields() {
        return new IntensityColorFields();
    }

    /**
     * Create an instance of {@link CartesianFields }
     * 
     */
    public CartesianFields createCartesianFields() {
        return new CartesianFields();
    }

    /**
     * Create an instance of {@link Rotation }
     * 
     */
    public Rotation createRotation() {
        return new Rotation();
    }

    /**
     * Create an instance of {@link CylindricalRepresentation }
     * 
     */
    public CylindricalRepresentation createCylindricalRepresentation() {
        return new CylindricalRepresentation();
    }

    /**
     * Create an instance of {@link E57Image }
     * 
     */
    public E57Image createE57Image() {
        return new E57Image();
    }

    /**
     * Create an instance of {@link Pose }
     * 
     */
    public Pose createPose() {
        return new Pose();
    }

    /**
     * Create an instance of {@link Translation }
     * 
     */
    public Translation createTranslation() {
        return new Translation();
    }

    /**
     * Create an instance of {@link VisualRefRepresentation }
     * 
     */
    public VisualRefRepresentation createVisualRefRepresentation() {
        return new VisualRefRepresentation();
    }

    /**
     * Create an instance of {@link SphericalRepresentation }
     * 
     */
    public SphericalRepresentation createSphericalRepresentation() {
        return new SphericalRepresentation();
    }

    /**
     * Create an instance of {@link PinholeRepresentation }
     * 
     */
    public PinholeRepresentation createPinholeRepresentation() {
        return new PinholeRepresentation();
    }

    /**
     * Create an instance of {@link E57M }
     * 
     */
    public E57M createE57M() {
        return new E57M();
    }

    /**
     * Create an instance of {@link E57Root }
     * 
     */
    public E57Root createE57Root() {
        return new E57Root();
    }

    /**
     * Create an instance of {@link E57Scan }
     * 
     */
    public E57Scan createE57Scan() {
        return new E57Scan();
    }

    /**
     * Create an instance of {@link IndexBounds }
     * 
     */
    public IndexBounds createIndexBounds() {
        return new IndexBounds();
    }

    /**
     * Create an instance of {@link CartesianBounds }
     * 
     */
    public CartesianBounds createCartesianBounds() {
        return new CartesianBounds();
    }

    /**
     * Create an instance of {@link Sphericalbounds }
     * 
     */
    public Sphericalbounds createSphericalbounds() {
        return new Sphericalbounds();
    }

    /**
     * Create an instance of {@link IntensityLimits }
     * 
     */
    public IntensityLimits createIntensityLimits() {
        return new IntensityLimits();
    }

    /**
     * Create an instance of {@link ColorLimits }
     * 
     */
    public ColorLimits createColorLimits() {
        return new ColorLimits();
    }

    /**
     * Create an instance of {@link PointFields }
     * 
     */
    public PointFields createPointFields() {
        return new PointFields();
    }

    /**
     * Create an instance of {@link SphericalFields }
     * 
     */
    public SphericalFields createSphericalFields() {
        return new SphericalFields();
    }

    /**
     * Create an instance of {@link PointRange }
     * 
     */
    public PointRange createPointRange() {
        return new PointRange();
    }

    /**
     * Create an instance of {@link Angles }
     * 
     */
    public Angles createAngles() {
        return new Angles();
    }

    /**
     * Create an instance of {@link IndexFields }
     * 
     */
    public IndexFields createIndexFields() {
        return new IndexFields();
    }

    /**
     * Create an instance of {@link TimeFields }
     * 
     */
    public TimeFields createTimeFields() {
        return new TimeFields();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "focal_length")
    public JAXBElement<BigDecimal> createFocalLength(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_FocalLength_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cartesian_invalid_state_field")
    public JAXBElement<Boolean> createCartesianInvalidStateField(Boolean value) {
        return new JAXBElement<Boolean>(_CartesianInvalidStateField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cartesian_y_field")
    public JAXBElement<Boolean> createCartesianYField(Boolean value) {
        return new JAXBElement<Boolean>(_CartesianYField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pointSize")
    public JAXBElement<Integer> createPointSize(Integer value) {
        return new JAXBElement<Integer>(_PointSize_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperature")
    public JAXBElement<BigDecimal> createTemperature(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Temperature_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "range_maximum")
    public JAXBElement<BigDecimal> createRangeMaximum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RangeMaximum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image_size")
    public JAXBElement<Short> createImageSize(Short value) {
        return new JAXBElement<Short>(_ImageSize_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_color_invalid_field")
    public JAXBElement<Boolean> createIsColorInvalidField(Boolean value) {
        return new JAXBElement<Boolean>(_IsColorInvalidField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intensity_field")
    public JAXBElement<Boolean> createIntensityField(Boolean value) {
        return new JAXBElement<Boolean>(_IntensityField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sensor_hardware_version")
    public JAXBElement<String> createSensorHardwareVersion(String value) {
        return new JAXBElement<String>(_SensorHardwareVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cartesian_x_field")
    public JAXBElement<Boolean> createCartesianXField(Boolean value) {
        return new JAXBElement<Boolean>(_CartesianXField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scan_size")
    public JAXBElement<Byte> createScanSize(Byte value) {
        return new JAXBElement<Byte>(_ScanSize_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relative_humidity")
    public JAXBElement<Byte> createRelativeHumidity(Byte value) {
        return new JAXBElement<Byte>(_RelativeHumidity_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "azimuth_minimum")
    public JAXBElement<Byte> createAzimuthMinimum(Byte value) {
        return new JAXBElement<Byte>(_AzimuthMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "spherical_elevation_field")
    public JAXBElement<Boolean> createSphericalElevationField(Boolean value) {
        return new JAXBElement<Boolean>(_SphericalElevationField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "principal_point_y")
    public JAXBElement<BigDecimal> createPrincipalPointY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PrincipalPointY_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "principal_point_x")
    public JAXBElement<Short> createPrincipalPointX(Short value) {
        return new JAXBElement<Short>(_PrincipalPointX_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "angle_scaled_integer")
    public JAXBElement<Byte> createAngleScaledInteger(Byte value) {
        return new JAXBElement<Byte>(_AngleScaledInteger_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scan_count")
    public JAXBElement<Byte> createScanCount(Byte value) {
        return new JAXBElement<Byte>(_ScanCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_red_minimum")
    public JAXBElement<Byte> createColorRedMinimum(Byte value) {
        return new JAXBElement<Byte>(_ColorRedMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "radius")
    public JAXBElement<BigDecimal> createRadius(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Radius_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_blue_maximum")
    public JAXBElement<Short> createColorBlueMaximum(Short value) {
        return new JAXBElement<Short>(_ColorBlueMaximum_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "point_range_scaled_integer")
    public JAXBElement<Double> createPointRangeScaledInteger(Double value) {
        return new JAXBElement<Double>(_PointRangeScaledInteger_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_red_field")
    public JAXBElement<Boolean> createColorRedField(Boolean value) {
        return new JAXBElement<Boolean>(_ColorRedField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image_height")
    public JAXBElement<Short> createImageHeight(Short value) {
        return new JAXBElement<Short>(_ImageHeight_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "row_minimum")
    public JAXBElement<Byte> createRowMinimum(Byte value) {
        return new JAXBElement<Byte>(_RowMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<BigDecimal> createVersion(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Version_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "azimuth_maximum")
    public JAXBElement<Double> createAzimuthMaximum(Double value) {
        return new JAXBElement<Double>(_AzimuthMaximum_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intensity_scaled_integer")
    public JAXBElement<BigDecimal> createIntensityScaledInteger(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_IntensityScaledInteger_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return_index_field")
    public JAXBElement<Boolean> createReturnIndexField(Boolean value) {
        return new JAXBElement<Boolean>(_ReturnIndexField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "col_minimum")
    public JAXBElement<Byte> createColMinimum(Byte value) {
        return new JAXBElement<Byte>(_ColMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image_mask_size")
    public JAXBElement<Byte> createImageMaskSize(Byte value) {
        return new JAXBElement<Byte>(_ImageMaskSize_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intensity_minimum")
    public JAXBElement<Byte> createIntensityMinimum(Byte value) {
        return new JAXBElement<Byte>(_IntensityMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return_maximum")
    public JAXBElement<Byte> createReturnMaximum(Byte value) {
        return new JAXBElement<Byte>(_ReturnMaximum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "angle_maximum")
    public JAXBElement<Byte> createAngleMaximum(Byte value) {
        return new JAXBElement<Byte>(_AngleMaximum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "original_guids")
    public JAXBElement<String> createOriginalGuids(String value) {
        return new JAXBElement<String>(_OriginalGuids_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "acquisition_start")
    public JAXBElement<XMLGregorianCalendar> createAcquisitionStart(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AcquisitionStart_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "column_index_field")
    public JAXBElement<Boolean> createColumnIndexField(Boolean value) {
        return new JAXBElement<Boolean>(_ColumnIndexField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "acquisition_datetime")
    public JAXBElement<XMLGregorianCalendar> createAcquisitionDatetime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AcquisitionDatetime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "w")
    public JAXBElement<BigDecimal> createW(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_W_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elevation_maximum")
    public JAXBElement<BigDecimal> createElevationMaximum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ElevationMaximum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "column_index_maximum")
    public JAXBElement<Long> createColumnIndexMaximum(Long value) {
        return new JAXBElement<Long>(_ColumnIndexMaximum_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sensor_software_version")
    public JAXBElement<String> createSensorSoftwareVersion(String value) {
        return new JAXBElement<String>(_SensorSoftwareVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "z")
    public JAXBElement<Double> createZ(Double value) {
        return new JAXBElement<Double>(_Z_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "y")
    public JAXBElement<BigDecimal> createY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Y_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "y_maximum")
    public JAXBElement<BigDecimal> createYMaximum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_YMaximum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x")
    public JAXBElement<BigDecimal> createX(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_X_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "spherical_azimuth_field")
    public JAXBElement<Boolean> createSphericalAzimuthField(Boolean value) {
        return new JAXBElement<Boolean>(_SphericalAzimuthField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "point_range_minimum")
    public JAXBElement<BigDecimal> createPointRangeMinimum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PointRangeMinimum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_green_maximum")
    public JAXBElement<Short> createColorGreenMaximum(Short value) {
        return new JAXBElement<Short>(_ColorGreenMaximum_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_green_minimum")
    public JAXBElement<Byte> createColorGreenMinimum(Byte value) {
        return new JAXBElement<Byte>(_ColorGreenMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return_count_field")
    public JAXBElement<Boolean> createReturnCountField(Boolean value) {
        return new JAXBElement<Boolean>(_ReturnCountField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_intensity_invalid_field")
    public JAXBElement<Boolean> createIsIntensityInvalidField(Boolean value) {
        return new JAXBElement<Boolean>(_IsIntensityInvalidField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image_width")
    public JAXBElement<Short> createImageWidth(Short value) {
        return new JAXBElement<Short>(_ImageWidth_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sensor_serial_number")
    public JAXBElement<String> createSensorSerialNumber(String value) {
        return new JAXBElement<String>(_SensorSerialNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "acquisition_end")
    public JAXBElement<XMLGregorianCalendar> createAcquisitionEnd(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AcquisitionEnd_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "row_maximum")
    public JAXBElement<Short> createRowMaximum(Short value) {
        return new JAXBElement<Short>(_RowMaximum_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_blue_field")
    public JAXBElement<Boolean> createColorBlueField(Boolean value) {
        return new JAXBElement<Boolean>(_ColorBlueField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "row_index_maximum")
    public JAXBElement<Long> createRowIndexMaximum(Long value) {
        return new JAXBElement<Long>(_RowIndexMaximum_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "coordinate_metadata")
    public JAXBElement<String> createCoordinateMetadata(String value) {
        return new JAXBElement<String>(_CoordinateMetadata_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "z_minimum")
    public JAXBElement<BigDecimal> createZMinimum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ZMinimum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "atmospheric_pressure")
    public JAXBElement<Integer> createAtmosphericPressure(Integer value) {
        return new JAXBElement<Integer>(_AtmosphericPressure_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creation_datetime")
    public JAXBElement<XMLGregorianCalendar> createCreationDatetime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreationDatetime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "spherical_invalid_state_field")
    public JAXBElement<Boolean> createSphericalInvalidStateField(Boolean value) {
        return new JAXBElement<Boolean>(_SphericalInvalidStateField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "col_maximum")
    public JAXBElement<Short> createColMaximum(Short value) {
        return new JAXBElement<Short>(_ColMaximum_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x_minimum")
    public JAXBElement<BigDecimal> createXMinimum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_XMinimum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sensor_firmware_version")
    public JAXBElement<String> createSensorFirmwareVersion(String value) {
        return new JAXBElement<String>(_SensorFirmwareVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pixel_height")
    public JAXBElement<BigDecimal> createPixelHeight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PixelHeight_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cartesian_z_field")
    public JAXBElement<Boolean> createCartesianZField(Boolean value) {
        return new JAXBElement<Boolean>(_CartesianZField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "representation")
    public JAXBElement<String> createRepresentation(String value) {
        return new JAXBElement<String>(_Representation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_red_maximum")
    public JAXBElement<Short> createColorRedMaximum(Short value) {
        return new JAXBElement<Short>(_ColorRedMaximum_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time_Maximum")
    public JAXBElement<Byte> createTimeMaximum(Byte value) {
        return new JAXBElement<Byte>(_TimeMaximum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "spherical_range_field")
    public JAXBElement<Boolean> createSphericalRangeField(Boolean value) {
        return new JAXBElement<Boolean>(_SphericalRangeField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jpeg_image_size")
    public JAXBElement<Integer> createJpegImageSize(Integer value) {
        return new JAXBElement<Integer>(_JpegImageSize_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image_count")
    public JAXBElement<Byte> createImageCount(Byte value) {
        return new JAXBElement<Byte>(_ImageCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elevation_minimum")
    public JAXBElement<BigDecimal> createElevationMinimum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ElevationMinimum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time_stamp_field")
    public JAXBElement<Boolean> createTimeStampField(Boolean value) {
        return new JAXBElement<Boolean>(_TimeStampField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_Time_Stamp_invalid")
    public JAXBElement<Boolean> createIsTimeStampInvalid(Boolean value) {
        return new JAXBElement<Boolean>(_IsTimeStampInvalid_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "row_index_field")
    public JAXBElement<Boolean> createRowIndexField(Boolean value) {
        return new JAXBElement<Boolean>(_RowIndexField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sensor_vendor")
    public JAXBElement<String> createSensorVendor(String value) {
        return new JAXBElement<String>(_SensorVendor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sensor_model")
    public JAXBElement<String> createSensorModel(String value) {
        return new JAXBElement<String>(_SensorModel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pixel_width")
    public JAXBElement<BigDecimal> createPixelWidth(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PixelWidth_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_green_field")
    public JAXBElement<Boolean> createColorGreenField(Boolean value) {
        return new JAXBElement<Boolean>(_ColorGreenField_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "associated_data3D_guid")
    public JAXBElement<String> createAssociatedData3DGuid(String value) {
        return new JAXBElement<String>(_AssociatedData3DGuid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "point_range_maximum")
    public JAXBElement<BigDecimal> createPointRangeMaximum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PointRangeMaximum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "y_minimum")
    public JAXBElement<BigDecimal> createYMinimum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_YMinimum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x_maximum")
    public JAXBElement<BigDecimal> createXMaximum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_XMaximum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "png_image_size")
    public JAXBElement<Integer> createPngImageSize(Integer value) {
        return new JAXBElement<Integer>(_PngImageSize_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "z_maximum")
    public JAXBElement<BigDecimal> createZMaximum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ZMaximum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "range_minimum")
    public JAXBElement<BigDecimal> createRangeMinimum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RangeMinimum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "angle_minimum")
    public JAXBElement<Byte> createAngleMinimum(Byte value) {
        return new JAXBElement<Byte>(_AngleMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_blue_minimum")
    public JAXBElement<Byte> createColorBlueMinimum(Byte value) {
        return new JAXBElement<Byte>(_ColorBlueMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return_minimum")
    public JAXBElement<Byte> createReturnMinimum(Byte value) {
        return new JAXBElement<Byte>(_ReturnMinimum_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intensity_maximum")
    public JAXBElement<Byte> createIntensityMaximum(Byte value) {
        return new JAXBElement<Byte>(_IntensityMaximum_QNAME, Byte.class, null, value);
    }

}
