//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}spherical_range_field"/>
 *         &lt;element ref="{}spherical_elevation_field"/>
 *         &lt;element ref="{}spherical_azimuth_field"/>
 *         &lt;element ref="{}spherical_invalid_state_field"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sphericalRangeField",
    "sphericalElevationField",
    "sphericalAzimuthField",
    "sphericalInvalidStateField"
})
@XmlRootElement(name = "spherical_fields")
public class SphericalFields {

    @XmlElement(name = "spherical_range_field")
    protected boolean sphericalRangeField;
    @XmlElement(name = "spherical_elevation_field")
    protected boolean sphericalElevationField;
    @XmlElement(name = "spherical_azimuth_field")
    protected boolean sphericalAzimuthField;
    @XmlElement(name = "spherical_invalid_state_field")
    protected boolean sphericalInvalidStateField;

    /**
     * Gets the value of the sphericalRangeField property.
     * 
     */
    public boolean isSphericalRangeField() {
        return sphericalRangeField;
    }

    /**
     * Sets the value of the sphericalRangeField property.
     * 
     */
    public void setSphericalRangeField(boolean value) {
        this.sphericalRangeField = value;
    }

    /**
     * Gets the value of the sphericalElevationField property.
     * 
     */
    public boolean isSphericalElevationField() {
        return sphericalElevationField;
    }

    /**
     * Sets the value of the sphericalElevationField property.
     * 
     */
    public void setSphericalElevationField(boolean value) {
        this.sphericalElevationField = value;
    }

    /**
     * Gets the value of the sphericalAzimuthField property.
     * 
     */
    public boolean isSphericalAzimuthField() {
        return sphericalAzimuthField;
    }

    /**
     * Sets the value of the sphericalAzimuthField property.
     * 
     */
    public void setSphericalAzimuthField(boolean value) {
        this.sphericalAzimuthField = value;
    }

    /**
     * Gets the value of the sphericalInvalidStateField property.
     * 
     */
    public boolean isSphericalInvalidStateField() {
        return sphericalInvalidStateField;
    }

    /**
     * Sets the value of the sphericalInvalidStateField property.
     * 
     */
    public void setSphericalInvalidStateField(boolean value) {
        this.sphericalInvalidStateField = value;
    }

}
