//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}time_stamp_field"/>
 *         &lt;element ref="{}is_Time_Stamp_invalid"/>
 *         &lt;element ref="{}time_Maximum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timeStampField",
    "isTimeStampInvalid",
    "timeMaximum"
})
@XmlRootElement(name = "time_fields")
public class TimeFields {

    @XmlElement(name = "time_stamp_field")
    protected boolean timeStampField;
    @XmlElement(name = "is_Time_Stamp_invalid")
    protected boolean isTimeStampInvalid;
    @XmlElement(name = "time_Maximum")
    protected byte timeMaximum;

    /**
     * Gets the value of the timeStampField property.
     * 
     */
    public boolean isTimeStampField() {
        return timeStampField;
    }

    /**
     * Sets the value of the timeStampField property.
     * 
     */
    public void setTimeStampField(boolean value) {
        this.timeStampField = value;
    }

    /**
     * Gets the value of the isTimeStampInvalid property.
     * 
     */
    public boolean isIsTimeStampInvalid() {
        return isTimeStampInvalid;
    }

    /**
     * Sets the value of the isTimeStampInvalid property.
     * 
     */
    public void setIsTimeStampInvalid(boolean value) {
        this.isTimeStampInvalid = value;
    }

    /**
     * Gets the value of the timeMaximum property.
     * 
     */
    public byte getTimeMaximum() {
        return timeMaximum;
    }

    /**
     * Sets the value of the timeMaximum property.
     * 
     */
    public void setTimeMaximum(byte value) {
        this.timeMaximum = value;
    }

}
