//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 05:42:14 PM CEST 
//


package generated_e57;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}jpeg_image_size"/>
 *         &lt;element ref="{}png_image_size"/>
 *         &lt;element ref="{}image_mask_size"/>
 *         &lt;element ref="{}image_width"/>
 *         &lt;element ref="{}image_height"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jpegImageSize",
    "pngImageSize",
    "imageMaskSize",
    "imageWidth",
    "imageHeight"
})
@XmlRootElement(name = "visual_ref_representation")
public class VisualRefRepresentation {

    @XmlElement(name = "jpeg_image_size")
    protected int jpegImageSize;
    @XmlElement(name = "png_image_size")
    protected int pngImageSize;
    @XmlElement(name = "image_mask_size")
    protected byte imageMaskSize;
    @XmlElement(name = "image_width")
    protected short imageWidth;
    @XmlElement(name = "image_height")
    protected short imageHeight;

    /**
     * Gets the value of the jpegImageSize property.
     * 
     */
    public int getJpegImageSize() {
        return jpegImageSize;
    }

    /**
     * Sets the value of the jpegImageSize property.
     * 
     */
    public void setJpegImageSize(int value) {
        this.jpegImageSize = value;
    }

    /**
     * Gets the value of the pngImageSize property.
     * 
     */
    public int getPngImageSize() {
        return pngImageSize;
    }

    /**
     * Sets the value of the pngImageSize property.
     * 
     */
    public void setPngImageSize(int value) {
        this.pngImageSize = value;
    }

    /**
     * Gets the value of the imageMaskSize property.
     * 
     */
    public byte getImageMaskSize() {
        return imageMaskSize;
    }

    /**
     * Sets the value of the imageMaskSize property.
     * 
     */
    public void setImageMaskSize(byte value) {
        this.imageMaskSize = value;
    }

    /**
     * Gets the value of the imageWidth property.
     * 
     */
    public short getImageWidth() {
        return imageWidth;
    }

    /**
     * Sets the value of the imageWidth property.
     * 
     */
    public void setImageWidth(short value) {
        this.imageWidth = value;
    }

    /**
     * Gets the value of the imageHeight property.
     * 
     */
    public short getImageHeight() {
        return imageHeight;
    }

    /**
     * Sets the value of the imageHeight property.
     * 
     */
    public void setImageHeight(short value) {
        this.imageHeight = value;
    }

}
