//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 09:52:13 AM CEST 
//


package generated_e571;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated_e571 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated_e571
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link E57M }
     * 
     */
    public E57M createE57M() {
        return new E57M();
    }

    /**
     * Create an instance of {@link E57M.E57Image }
     * 
     */
    public E57M.E57Image createE57ME57Image() {
        return new E57M.E57Image();
    }

    /**
     * Create an instance of {@link E57M.E57Image.Pose }
     * 
     */
    public E57M.E57Image.Pose createE57ME57ImagePose() {
        return new E57M.E57Image.Pose();
    }

    /**
     * Create an instance of {@link E57M.E57Scan }
     * 
     */
    public E57M.E57Scan createE57ME57Scan() {
        return new E57M.E57Scan();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.PointFields }
     * 
     */
    public E57M.E57Scan.PointFields createE57ME57ScanPointFields() {
        return new E57M.E57Scan.PointFields();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.Pose }
     * 
     */
    public E57M.E57Scan.Pose createE57ME57ScanPose() {
        return new E57M.E57Scan.Pose();
    }

    /**
     * Create an instance of {@link E57M.E57Root }
     * 
     */
    public E57M.E57Root createE57ME57Root() {
        return new E57M.E57Root();
    }

    /**
     * Create an instance of {@link E57M.E57Image.VisualRefRepresentation }
     * 
     */
    public E57M.E57Image.VisualRefRepresentation createE57ME57ImageVisualRefRepresentation() {
        return new E57M.E57Image.VisualRefRepresentation();
    }

    /**
     * Create an instance of {@link E57M.E57Image.SphericalRepresentation }
     * 
     */
    public E57M.E57Image.SphericalRepresentation createE57ME57ImageSphericalRepresentation() {
        return new E57M.E57Image.SphericalRepresentation();
    }

    /**
     * Create an instance of {@link E57M.E57Image.PinholeRepresentation }
     * 
     */
    public E57M.E57Image.PinholeRepresentation createE57ME57ImagePinholeRepresentation() {
        return new E57M.E57Image.PinholeRepresentation();
    }

    /**
     * Create an instance of {@link E57M.E57Image.CylindricalRepresentation }
     * 
     */
    public E57M.E57Image.CylindricalRepresentation createE57ME57ImageCylindricalRepresentation() {
        return new E57M.E57Image.CylindricalRepresentation();
    }

    /**
     * Create an instance of {@link E57M.E57Image.Pose.Rotation }
     * 
     */
    public E57M.E57Image.Pose.Rotation createE57ME57ImagePoseRotation() {
        return new E57M.E57Image.Pose.Rotation();
    }

    /**
     * Create an instance of {@link E57M.E57Image.Pose.Translation }
     * 
     */
    public E57M.E57Image.Pose.Translation createE57ME57ImagePoseTranslation() {
        return new E57M.E57Image.Pose.Translation();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.IndexBounds }
     * 
     */
    public E57M.E57Scan.IndexBounds createE57ME57ScanIndexBounds() {
        return new E57M.E57Scan.IndexBounds();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.CartesianBounds }
     * 
     */
    public E57M.E57Scan.CartesianBounds createE57ME57ScanCartesianBounds() {
        return new E57M.E57Scan.CartesianBounds();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.Sphericalbounds }
     * 
     */
    public E57M.E57Scan.Sphericalbounds createE57ME57ScanSphericalbounds() {
        return new E57M.E57Scan.Sphericalbounds();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.IntensityLimits }
     * 
     */
    public E57M.E57Scan.IntensityLimits createE57ME57ScanIntensityLimits() {
        return new E57M.E57Scan.IntensityLimits();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.ColorLimits }
     * 
     */
    public E57M.E57Scan.ColorLimits createE57ME57ScanColorLimits() {
        return new E57M.E57Scan.ColorLimits();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.PointFields.CartesianFields }
     * 
     */
    public E57M.E57Scan.PointFields.CartesianFields createE57ME57ScanPointFieldsCartesianFields() {
        return new E57M.E57Scan.PointFields.CartesianFields();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.PointFields.SphericalFields }
     * 
     */
    public E57M.E57Scan.PointFields.SphericalFields createE57ME57ScanPointFieldsSphericalFields() {
        return new E57M.E57Scan.PointFields.SphericalFields();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.PointFields.PointRange }
     * 
     */
    public E57M.E57Scan.PointFields.PointRange createE57ME57ScanPointFieldsPointRange() {
        return new E57M.E57Scan.PointFields.PointRange();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.PointFields.Angles }
     * 
     */
    public E57M.E57Scan.PointFields.Angles createE57ME57ScanPointFieldsAngles() {
        return new E57M.E57Scan.PointFields.Angles();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.PointFields.IndexFields }
     * 
     */
    public E57M.E57Scan.PointFields.IndexFields createE57ME57ScanPointFieldsIndexFields() {
        return new E57M.E57Scan.PointFields.IndexFields();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.PointFields.TimeFields }
     * 
     */
    public E57M.E57Scan.PointFields.TimeFields createE57ME57ScanPointFieldsTimeFields() {
        return new E57M.E57Scan.PointFields.TimeFields();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.PointFields.IntensityColorFields }
     * 
     */
    public E57M.E57Scan.PointFields.IntensityColorFields createE57ME57ScanPointFieldsIntensityColorFields() {
        return new E57M.E57Scan.PointFields.IntensityColorFields();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.Pose.Rotation }
     * 
     */
    public E57M.E57Scan.Pose.Rotation createE57ME57ScanPoseRotation() {
        return new E57M.E57Scan.Pose.Rotation();
    }

    /**
     * Create an instance of {@link E57M.E57Scan.Pose.Translation }
     * 
     */
    public E57M.E57Scan.Pose.Translation createE57ME57ScanPoseTranslation() {
        return new E57M.E57Scan.Pose.Translation();
    }

}
