//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 01:01:42 PM CEST 
//


package generated_buildm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Identifier"/>
 *         &lt;element ref="{}creator"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}dateCreated"/>
 *         &lt;element ref="{}filesize"/>
 *         &lt;element ref="{}isPartOf"/>
 *         &lt;element ref="{}hasPart"/>
 *         &lt;element ref="{}format"/>
 *         &lt;element ref="{}hasType"/>
 *         &lt;element ref="{}hasFormatDetails"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}provenance"/>
 *         &lt;element ref="{}license"/>
 *         &lt;element ref="{}unitCode"/>
 *         &lt;element ref="{}levelOfDetail"/>
 *         &lt;element ref="{}event"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifier",
    "creator",
    "name",
    "dateCreated",
    "filesize",
    "isPartOf",
    "hasPart",
    "format",
    "hasType",
    "hasFormatDetails",
    "description",
    "provenance",
    "license",
    "unitCode",
    "levelOfDetail",
    "event"
})
@XmlRootElement(name = "digitalObject")
public class DigitalObject {

    @XmlElement(name = "Identifier", required = true)
    protected String identifier;
    @XmlElement(required = true)
    protected String creator;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected XMLGregorianCalendar dateCreated;
    protected long filesize;
    @XmlElement(required = true)
    protected String isPartOf;
    @XmlElement(required = true)
    protected String hasPart;
    @XmlElement(required = true)
    protected String format;
    @XmlElement(required = true)
    protected String hasType;
    @XmlElement(required = true)
    protected String hasFormatDetails;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String provenance;
    @XmlElement(required = true)
    protected String license;
    @XmlElement(required = true)
    protected String unitCode;
    @XmlElement(required = true)
    protected String levelOfDetail;
    @XmlElement(required = true)
    protected String event;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreated(XMLGregorianCalendar value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the filesize property.
     * 
     */
    public long getFilesize() {
        return filesize;
    }

    /**
     * Sets the value of the filesize property.
     * 
     */
    public void setFilesize(long value) {
        this.filesize = value;
    }

    /**
     * Gets the value of the isPartOf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPartOf() {
        return isPartOf;
    }

    /**
     * Sets the value of the isPartOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPartOf(String value) {
        this.isPartOf = value;
    }

    /**
     * Gets the value of the hasPart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasPart() {
        return hasPart;
    }

    /**
     * Sets the value of the hasPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasPart(String value) {
        this.hasPart = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the hasType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasType() {
        return hasType;
    }

    /**
     * Sets the value of the hasType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasType(String value) {
        this.hasType = value;
    }

    /**
     * Gets the value of the hasFormatDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasFormatDetails() {
        return hasFormatDetails;
    }

    /**
     * Sets the value of the hasFormatDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasFormatDetails(String value) {
        this.hasFormatDetails = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the provenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvenance() {
        return provenance;
    }

    /**
     * Sets the value of the provenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvenance(String value) {
        this.provenance = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicense(String value) {
        this.license = value;
    }

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

    /**
     * Gets the value of the levelOfDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelOfDetail() {
        return levelOfDetail;
    }

    /**
     * Sets the value of the levelOfDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelOfDetail(String value) {
        this.levelOfDetail = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

}
