//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 02:19:00 PM CEST 
//


package generated_buildm1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated_buildm1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated_buildm1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Buildm }
     * 
     */
    public Buildm createBuildm() {
        return new Buildm();
    }

    /**
     * Create an instance of {@link Buildm.PhysicalAsset }
     * 
     */
    public Buildm.PhysicalAsset createBuildmPhysicalAsset() {
        return new Buildm.PhysicalAsset();
    }

    /**
     * Create an instance of {@link Buildm.DigitalObject }
     * 
     */
    public Buildm.DigitalObject createBuildmDigitalObject() {
        return new Buildm.DigitalObject();
    }

}
