//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 09:52:28 AM CEST 
//


package generated_ifcm1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="preprocessor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="originatingSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="authorization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fileSchema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="viewDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="exportOptions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ifcparameters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ifcApplication" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="IfcGeometricRepresentationContext" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ifcSiUnit" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="quantities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="floorCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="roomCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="wallCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="windowsCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="doorCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="pipeCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="columnCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="numberOfComponents" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="numberOfRelations" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="numberOfActors" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="informationMetric">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numberOfEntityTypesUsed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="numberOfTotalEntitiesUsed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="optionalAttributes" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Dependencies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="webResourceLink" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "ifcparameters",
    "quantities",
    "informationMetric",
    "dependencies"
})
@XmlRootElement(name = "ifcm")
public class Ifcm {

    @XmlElement(required = true)
    protected Ifcm.Header header;
    @XmlElement(required = true)
    protected Ifcm.Ifcparameters ifcparameters;
    @XmlElement(required = true)
    protected Ifcm.Quantities quantities;
    @XmlElement(required = true)
    protected Ifcm.InformationMetric informationMetric;
    @XmlElement(name = "Dependencies", required = true)
    protected Ifcm.Dependencies dependencies;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Ifcm.Header }
     *     
     */
    public Ifcm.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ifcm.Header }
     *     
     */
    public void setHeader(Ifcm.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the ifcparameters property.
     * 
     * @return
     *     possible object is
     *     {@link Ifcm.Ifcparameters }
     *     
     */
    public Ifcm.Ifcparameters getIfcparameters() {
        return ifcparameters;
    }

    /**
     * Sets the value of the ifcparameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ifcm.Ifcparameters }
     *     
     */
    public void setIfcparameters(Ifcm.Ifcparameters value) {
        this.ifcparameters = value;
    }

    /**
     * Gets the value of the quantities property.
     * 
     * @return
     *     possible object is
     *     {@link Ifcm.Quantities }
     *     
     */
    public Ifcm.Quantities getQuantities() {
        return quantities;
    }

    /**
     * Sets the value of the quantities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ifcm.Quantities }
     *     
     */
    public void setQuantities(Ifcm.Quantities value) {
        this.quantities = value;
    }

    /**
     * Gets the value of the informationMetric property.
     * 
     * @return
     *     possible object is
     *     {@link Ifcm.InformationMetric }
     *     
     */
    public Ifcm.InformationMetric getInformationMetric() {
        return informationMetric;
    }

    /**
     * Sets the value of the informationMetric property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ifcm.InformationMetric }
     *     
     */
    public void setInformationMetric(Ifcm.InformationMetric value) {
        this.informationMetric = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link Ifcm.Dependencies }
     *     
     */
    public Ifcm.Dependencies getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ifcm.Dependencies }
     *     
     */
    public void setDependencies(Ifcm.Dependencies value) {
        this.dependencies = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="webResourceLink" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "webResourceLink"
    })
    public static class Dependencies {

        protected List<String> webResourceLink;

        /**
         * Gets the value of the webResourceLink property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the webResourceLink property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWebResourceLink().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getWebResourceLink() {
            if (webResourceLink == null) {
                webResourceLink = new ArrayList<String>();
            }
            return this.webResourceLink;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="preprocessor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="originatingSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="authorization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="fileSchema" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="viewDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="exportOptions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "creationDate",
        "author",
        "organization",
        "preprocessor",
        "originatingSystem",
        "authorization",
        "fileSchema",
        "viewDefinition",
        "exportOptions"
    })
    public static class Header {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar creationDate;
        protected String author;
        protected String organization;
        protected String preprocessor;
        protected String originatingSystem;
        protected String authorization;
        @XmlElement(required = true)
        protected String fileSchema;
        @XmlElement(required = true)
        protected String viewDefinition;
        protected String exportOptions;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the creationDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreationDate() {
            return creationDate;
        }

        /**
         * Sets the value of the creationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreationDate(XMLGregorianCalendar value) {
            this.creationDate = value;
        }

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the organization property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrganization() {
            return organization;
        }

        /**
         * Sets the value of the organization property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrganization(String value) {
            this.organization = value;
        }

        /**
         * Gets the value of the preprocessor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreprocessor() {
            return preprocessor;
        }

        /**
         * Sets the value of the preprocessor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreprocessor(String value) {
            this.preprocessor = value;
        }

        /**
         * Gets the value of the originatingSystem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginatingSystem() {
            return originatingSystem;
        }

        /**
         * Sets the value of the originatingSystem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginatingSystem(String value) {
            this.originatingSystem = value;
        }

        /**
         * Gets the value of the authorization property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorization() {
            return authorization;
        }

        /**
         * Sets the value of the authorization property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorization(String value) {
            this.authorization = value;
        }

        /**
         * Gets the value of the fileSchema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileSchema() {
            return fileSchema;
        }

        /**
         * Sets the value of the fileSchema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileSchema(String value) {
            this.fileSchema = value;
        }

        /**
         * Gets the value of the viewDefinition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getViewDefinition() {
            return viewDefinition;
        }

        /**
         * Sets the value of the viewDefinition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setViewDefinition(String value) {
            this.viewDefinition = value;
        }

        /**
         * Gets the value of the exportOptions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExportOptions() {
            return exportOptions;
        }

        /**
         * Sets the value of the exportOptions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExportOptions(String value) {
            this.exportOptions = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ifcApplication" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="IfcGeometricRepresentationContext" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ifcSiUnit" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ifcApplication",
        "ifcGeometricRepresentationContext",
        "ifcSiUnit"
    })
    public static class Ifcparameters {

        protected List<String> ifcApplication;
        @XmlElement(name = "IfcGeometricRepresentationContext")
        protected List<String> ifcGeometricRepresentationContext;
        protected List<String> ifcSiUnit;

        /**
         * Gets the value of the ifcApplication property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ifcApplication property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIfcApplication().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getIfcApplication() {
            if (ifcApplication == null) {
                ifcApplication = new ArrayList<String>();
            }
            return this.ifcApplication;
        }

        /**
         * Gets the value of the ifcGeometricRepresentationContext property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ifcGeometricRepresentationContext property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIfcGeometricRepresentationContext().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getIfcGeometricRepresentationContext() {
            if (ifcGeometricRepresentationContext == null) {
                ifcGeometricRepresentationContext = new ArrayList<String>();
            }
            return this.ifcGeometricRepresentationContext;
        }

        /**
         * Gets the value of the ifcSiUnit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ifcSiUnit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIfcSiUnit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getIfcSiUnit() {
            if (ifcSiUnit == null) {
                ifcSiUnit = new ArrayList<String>();
            }
            return this.ifcSiUnit;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numberOfEntityTypesUsed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="numberOfTotalEntitiesUsed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="optionalAttributes" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numberOfEntityTypesUsed",
        "numberOfTotalEntitiesUsed",
        "optionalAttributes"
    })
    public static class InformationMetric {

        protected BigInteger numberOfEntityTypesUsed;
        protected BigInteger numberOfTotalEntitiesUsed;
        protected BigInteger optionalAttributes;

        /**
         * Gets the value of the numberOfEntityTypesUsed property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfEntityTypesUsed() {
            return numberOfEntityTypesUsed;
        }

        /**
         * Sets the value of the numberOfEntityTypesUsed property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfEntityTypesUsed(BigInteger value) {
            this.numberOfEntityTypesUsed = value;
        }

        /**
         * Gets the value of the numberOfTotalEntitiesUsed property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfTotalEntitiesUsed() {
            return numberOfTotalEntitiesUsed;
        }

        /**
         * Sets the value of the numberOfTotalEntitiesUsed property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfTotalEntitiesUsed(BigInteger value) {
            this.numberOfTotalEntitiesUsed = value;
        }

        /**
         * Gets the value of the optionalAttributes property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOptionalAttributes() {
            return optionalAttributes;
        }

        /**
         * Sets the value of the optionalAttributes property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOptionalAttributes(BigInteger value) {
            this.optionalAttributes = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="floorCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="roomCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="wallCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="windowsCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="doorCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="pipeCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="columnCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="numberOfComponents" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="numberOfRelations" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="numberOfActors" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "floorCount",
        "roomCount",
        "wallCount",
        "windowsCount",
        "doorCount",
        "pipeCount",
        "columnCount",
        "numberOfComponents",
        "numberOfRelations",
        "numberOfActors"
    })
    public static class Quantities {

        protected BigInteger floorCount;
        protected BigInteger roomCount;
        protected BigInteger wallCount;
        protected BigInteger windowsCount;
        protected BigInteger doorCount;
        protected BigInteger pipeCount;
        protected BigInteger columnCount;
        protected BigInteger numberOfComponents;
        protected BigInteger numberOfRelations;
        protected BigInteger numberOfActors;

        /**
         * Gets the value of the floorCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFloorCount() {
            return floorCount;
        }

        /**
         * Sets the value of the floorCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFloorCount(BigInteger value) {
            this.floorCount = value;
        }

        /**
         * Gets the value of the roomCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRoomCount() {
            return roomCount;
        }

        /**
         * Sets the value of the roomCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRoomCount(BigInteger value) {
            this.roomCount = value;
        }

        /**
         * Gets the value of the wallCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getWallCount() {
            return wallCount;
        }

        /**
         * Sets the value of the wallCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setWallCount(BigInteger value) {
            this.wallCount = value;
        }

        /**
         * Gets the value of the windowsCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getWindowsCount() {
            return windowsCount;
        }

        /**
         * Sets the value of the windowsCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setWindowsCount(BigInteger value) {
            this.windowsCount = value;
        }

        /**
         * Gets the value of the doorCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDoorCount() {
            return doorCount;
        }

        /**
         * Sets the value of the doorCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDoorCount(BigInteger value) {
            this.doorCount = value;
        }

        /**
         * Gets the value of the pipeCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPipeCount() {
            return pipeCount;
        }

        /**
         * Sets the value of the pipeCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPipeCount(BigInteger value) {
            this.pipeCount = value;
        }

        /**
         * Gets the value of the columnCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getColumnCount() {
            return columnCount;
        }

        /**
         * Sets the value of the columnCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setColumnCount(BigInteger value) {
            this.columnCount = value;
        }

        /**
         * Gets the value of the numberOfComponents property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfComponents() {
            return numberOfComponents;
        }

        /**
         * Sets the value of the numberOfComponents property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfComponents(BigInteger value) {
            this.numberOfComponents = value;
        }

        /**
         * Gets the value of the numberOfRelations property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfRelations() {
            return numberOfRelations;
        }

        /**
         * Sets the value of the numberOfRelations property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfRelations(BigInteger value) {
            this.numberOfRelations = value;
        }

        /**
         * Gets the value of the numberOfActors property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfActors() {
            return numberOfActors;
        }

        /**
         * Sets the value of the numberOfActors property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfActors(BigInteger value) {
            this.numberOfActors = value;
        }

    }

}
